<script lang="ts">
  import * as Accordion from '$lib/components/ui/accordion/index.js'
  import Button from '@/components/ui/button/button.svelte'
  import * as Card from '@/components/ui/card'
  import Bug from 'lucide-svelte/icons/bug'
  import Code from 'lucide-svelte/icons/code'
</script>

<div class="flex justify-around pb-4">
  <Button
    href="https://github.com/ddeeddii/eztools/issues"
    target="_blank"
    class="mt-2"
    variant="ghost"
  >
    <Bug class="mr-2 h-6 w-6" />
    Report bugs
  </Button>
  <Button href="https://github.com/ddeeddii/eztools" target="_blank" class="mt-2" variant="ghost">
    <Code class="mr-2 h-6 w-6" />
    Source code
  </Button>
</div>

<div class="flex flex-col gap-4">
  <span class="flex justify-center text-2xl font-semibold">Frequently Asked Questions</span>

  <Card.Root>
    <Card.Header class="flex items-center">
      <Card.Title class="text-xl">Mod Templates</Card.Title>
    </Card.Header>
    <Card.Content>
      <Accordion.Root>
        <Accordion.Item value="item-1">
          <Accordion.Trigger>What is a mod template?</Accordion.Trigger>
          <Accordion.Content>
            <div class="pt-1">
              <p>
                Mods generated by EzItems are made out of two parts: the <i>template</i> and the
                <i>data</i>.
              </p>
              <p>
                The <i>template</i> contains code that parses the <i>data</i> and displays the
                renamed items in game. Its file name is <code>main.lua</code>
              </p>
              <p>
                The <i>data</i> stores all of your changed item data - their names, descriptions,
                etc. Its file name is <code>data.lua</code>
              </p>
            </div>
          </Accordion.Content>
        </Accordion.Item>
        <Accordion.Item value="item-2">
          <Accordion.Trigger>How are the mod templates different?</Accordion.Trigger>
          <Accordion.Content>
            <div class="pt-1">
              <p>
                There are currently 3 available templates - <code>Default</code>,
                <code>REPENTOGON</code>
                and <code>Legacy</code>.
              </p>
              <p>
                <code>Default</code> is the most basic template. It only supports items and trinkets.
              </p>
              <p>
                <code>REPENTOGON</code> partially supports pocket items (cards, runes, souls, etc).
                However, it
                <span class="font-semibold"
                  >requires the user to have <a
                    class="underline underline-offset-4"
                    href="https://repentogon.com/"
                    target="_blank">REPENTOGON</a
                  > installed</span
                >
              </p>
            </div>
          </Accordion.Content>
        </Accordion.Item>
      </Accordion.Root>
    </Card.Content>
  </Card.Root>

  <Card.Root>
    <Card.Header class="flex items-center">
      <Card.Title class="text-xl">REPENTOGON Support</Card.Title>
    </Card.Header>
    <Card.Content>
      <Accordion.Root>
        <Accordion.Item value="item-1">
          <Accordion.Trigger>Why can't I change sprites of pocket items?</Accordion.Trigger>
          <Accordion.Content>
            <div class="flex flex-col gap-2 pt-1">
              <p>TL;DR - Pocket item sprites are very different from regular item sprites.</p>
              <p>
                The most important reason is that they are extremely incompatible with other mods
                that change pocket item sprites.
                <br />
                That is because they are stored in two different files (<code
                  >ui_cardfronts.png</code
                >
                and <code>ui_cardspills.png</code>) which contain all of the vanilla pocket items.
                <br />
                Modifying either file is not only difficult (due to fact the all of the sprites are in
                one file) but will overwrite any/all changes some other mode has made to the other file.
              </p>
              <p>
                On top of that, if the vanilla game were to one day update the sprite of any pocket
                item, a mod that hasn't been updated will overwrite the new vanilla sprite.
              </p>
              <p>
                However, if REPENTOGON adds a way to change pocket item sprites independently or at
                runtime, EzItems will be updated to support it.
              </p>
            </div>
          </Accordion.Content>
        </Accordion.Item>
      </Accordion.Root>
    </Card.Content>
  </Card.Root>
</div>
