<script lang="ts">
  import * as Accordion from '$lib/components/ui/accordion/index.js'
  import Button from '@/components/ui/button/button.svelte'
  import Bug from 'lucide-svelte/icons/bug'
  import Code from 'lucide-svelte/icons/code'
</script>

<div class="flex justify-around pb-4">
  <Button href="https://github.com/ddeeddii/eztools/" target="_blank" class="mt-2" variant="ghost">
    <Bug class="mr-2 h-6 w-6" />
    Report bugs
  </Button>
  <Button
    href="https://github.com/ddeeddii/eztools/issues"
    target="_blank"
    class="mt-2"
    variant="ghost"
  >
    <Code class="mr-2 h-6 w-6" />
    Source code
  </Button>
</div>

<div class="">
  <span class="flex justify-center text-xl font-semibold">Frequently Asked Questions</span>

  <span class="text-xl">Mod Templates</span>
  <Accordion.Root>
    <Accordion.Item value="template-help">
      <Accordion.Trigger>What is a mod template?</Accordion.Trigger>
      <Accordion.Content>
        <div class="pt-1">
          <p>
            Mods generated by EzItems are made out of two parts: the <i>template</i> and the
            <i>data</i>.
          </p>
          <p>
            The <i>template</i> contains code that parses the <i>data</i> and displays the renamed
            items in game. Its file name is <code>main.lua</code>
          </p>
          <p>
            The <i>data</i> stores all of your changed item data - their names, descriptions, etc.
            Its file name is <code>data.lua</code>
          </p>
        </div>
      </Accordion.Content>
    </Accordion.Item>
    <Accordion.Item value="template-info">
      <Accordion.Trigger>How are the mod templates different?</Accordion.Trigger>
      <Accordion.Content>
        <div class="pt-1">
          <p>
            There are currently 3 available templates - <code>Default</code>,
            <code>REPENTOGON</code>
            and <code>Legacy</code>.
          </p>
          <p>
            <code>Default</code> is the most basic template. It only supports items and trinkets.
          </p>
          <p>
            <code>REPENTOGON</code> supports pocket items (cards, runes, souls, etc). However, it
            <span class="font-semibold"
              >requires the user to have <a
                class="underline underline-offset-4"
                href="https://repentogon.com/"
                target="_blank">REPENTOGON</a
              > installed</span
            >
          </p>
          <p>
            <code>Legacy</code> is the old template used in the original EzItems. It is only here for
            compatibility reasons.
          </p>
        </div>
      </Accordion.Content>
    </Accordion.Item>
    <Accordion.Item value="template-choice">
      <Accordion.Trigger>Which one do I use?</Accordion.Trigger>
      <Accordion.Content>
        <div class="pt-1">
          For most cases, <code>Default</code> should be enough. If you want to add pocket items,
          use <code>REPENTOGON</code>.
        </div>
      </Accordion.Content>
    </Accordion.Item>
  </Accordion.Root>
  <h1 class="text-xl font-semibold">TODO - fill in the rest of the info page</h1>
</div>
